### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by mowshon** [loretoparisi/python-threading#1]
Hello!

I think you accidentally forget to leave my copyright in this file.

**My repo**: 
https://github.com/mowshon/bounded_pool_executor/blob/master/bounded_pool_executor/__init__.py

**Your file**: 
https://github.com/loretoparisi/python-threading/blob/master/bounded_pool_executor.py

My module is under MIT License, so you can use the code only with my copyright in them.

Thank you!

**Comment by loretoparisi** [comment]
@mowshon thanks a lot, I was searching the source: https://github.com/loretoparisi/python-threading#disclaimer
Do you have a copy I can add? 
Thank you.

**Comment by loretoparisi** [comment]
@mowshon I have added references to the original sources in https://github.com/loretoparisi/python-threading#disclaimer

Thank you for your question.
